apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 10
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: hyuntaeson/nginx:v1
        volumeMounts:
        - mountPath: /var/log/nginx
          name: log
        ports:
        - containerPort: 80
      volumes:
      - name: log
        nfs:
          server: 10.255.163.26
          path: /log