
apiVersion: apps/v1
kind: Deployment
metadata:
  name: was
spec:
  replicas: 5
  selector:
    matchLabels:
      app: was
  template:
    metadata:
      labels:
        app: was
    spec:
      containers:
      - name: was
        image: hifrodo/m-dev:tomcat_latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      initContainers:
      - name: wait-for-redis
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup redis-svc.default.svc.cluster.local; do echo waiting for redis-svc; sleep 2; done"]
      - name: wait-for-mysql
        image: busybox:1.28
        command: ['sh', '-c', "until nslookup db-0.mysql-svc.default.svc.cluster.local; do echo waiting for db-0.mysql-svc; sleep 2; done"]